// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSR_Clone.Data;

#nullable disable

namespace NSR_Clone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("NSR_Clone.ObjectFolder.AnalysisObject", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleClassDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbId");

                    b.HasIndex("SampleClassDbId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("NSR_Clone.ObjectFolder.BatchClass", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbId");

                    b.HasIndex("CustomerDbId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("NSR_Clone.ObjectFolder.CustomerObject", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CVR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DbId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("NSR_Clone.SampleClass.SampleClass", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BatchClassDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbId");

                    b.HasIndex("BatchClassDbId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("NSR_Clone.ObjectFolder.AnalysisObject", b =>
                {
                    b.HasOne("NSR_Clone.SampleClass.SampleClass", null)
                        .WithMany("Analysis")
                        .HasForeignKey("SampleClassDbId");
                });

            modelBuilder.Entity("NSR_Clone.ObjectFolder.BatchClass", b =>
                {
                    b.HasOne("NSR_Clone.ObjectFolder.CustomerObject", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerDbId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NSR_Clone.SampleClass.SampleClass", b =>
                {
                    b.HasOne("NSR_Clone.ObjectFolder.BatchClass", null)
                        .WithMany("Samples")
                        .HasForeignKey("BatchClassDbId");
                });

            modelBuilder.Entity("NSR_Clone.ObjectFolder.BatchClass", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("NSR_Clone.SampleClass.SampleClass", b =>
                {
                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
